### ISSUE TITLE
Datasource connection fails with Feb 2021 template on Server 2019

### ISSUE THREAD

**Issue by geoandrew** [nbrown02/FlowViz#23]
**Describe the bug**
I have been using an older version (7/9/2020) of the template successfully for some time. It still functions correctly.
I downloaded the latest version (2/9/2021) of the template and now error out on connection.

**To Reproduce**

1. Open fresh template
2. Enter connection string
3. Load

```
Organization
Loading blocked by failures with other queries.
Number of remaining items
Loading blocked by failures with other queries.
Number of weeks to forecast
Loading blocked by failures with other queries.
Data Refresh
Loading blocked by failures with other queries.
WorkItems Completed
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
WorkItems In Progress WIP
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
Dates
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
Project
Loading blocked by failures with other queries.
Areas
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
WorkItems (Count of InProgress)
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
WorkItems Blocked (since 1st Jan 20) - Do Not Edit
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
Daily Blocked Count
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 4, Error: The remote server returned an error: (400) Bad Request. OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
```

Using Power BI Desktop - Version: 2.88.1682.0 64-bit (December, 2020)
Internally hosted Azure DevOps Server 2019

**Comment by nbrown02** [comment]
Hey Andrew,

Thanks for your feedback. 

So my first guess is it's because the OData URL for Azure DevOps Server is different to the Azure DevOps Services one. I changed it recently so it was simpler for the user where they only needed to enter their Organization and Project rather than the long OData URL...

What does the URL look like for Azure Devops Server?

**Comment by geoandrew** [comment]
Thanks for the prompt reply!

http://[internal url]:8080/tfs/Integration/Clinical%20Data%20Exchange/

**Comment by nbrown02** [comment]
No worries, and it confirms what I suspected :(

Unfortunately this is just for Azure DevOps Services, not Server. The template changes I made mean it's now a lot harder for you to load your data (as it was only ever for AzDO Services). 

What you might want to try (and no guarantee this will work) is to:
1) Make sure your Organization/Project Name is entered (not the full URL)
2) In the blank screen you have, click 'Transform Data' 
3) Go to the _WorkItems Completed_ table and change this part (highlighted) of the URL:

![image](https://user-images.githubusercontent.com/29369962/107417801-dd828f00-6b0d-11eb-98fa-c440ef7ec1aa.png)

So in this case change it from:
https://analytics.dev.azure.com/" & Organization & "/" & Project & "/_odata/v3.0/

to

https://[internal url]:8080/tfs/" & Organization & "/" & Project & "/_odata/v3.0/

You have to have the right Organisation and Project Name in the parameters :)

3) If that works, you'll need to do that for the following tables:

- WorkItems In Progress WIP
- Dates
- Areas
- WorkItems (Count of InProgress)
- WorkItems Blocked (since 1st Jan 20) - Do Not Edit
- Daily Blocked Count

Let me know if that works, and I'll see if I can change the underlying template to accommodate Azure DevOps Server 👍

**Comment by geoandrew** [comment]
Thanks for the great response.

I was able to go through an edit the data source for all the tables. However, that results in another error:

`{"$id":"1","innerException":null,"message":"VS403500: The v3.0 OData endpoint for Analytics is not supported. VS403503: Information on the latest recommended version is available here: https://go.microsoft.com/fwlink/?linkid=856818.","typeName":"Microsoft.VisualStudio.Services.Analytics.UnsupportedODataModelVersionException, Microsoft.VisualStudio.Services.Analytics.Server","typeKey":"UnsupportedODataModelVersionException","errorCode":0,"eventId":3000}`

Looks like my issue is Server Version.
Time to ask for an update!

Thanks again.

**Comment by nbrown02** [comment]
No worries, it may be worth changing 3.0 to 1.0 or 2.0 - not entirely sure what version Server uses, I'm glad my guess work helped though!

**Comment by nbrown02** [comment]
@geoandrew I've been working on an Azure DevOps Server version - would you be open to helping test?

**Comment by geoandrew** [comment]
Yes, would be happy to test.
We are currently on Server 2019 - fyi.

**Comment by nbrown02** [comment]
I've added a new template to the repo which someone else has tested (working for them) - mind taking a look?
