### ISSUE TITLE
Error on refreshing data in workspace

### ISSUE THREAD

**Issue by matkinsonPB** [nbrown02/FlowViz#85]
Firstly, FlowViz is an incredible offering. I'm impressed at the capability provided and the support offered in this template. I've lost track of the hours expended attempting to mine ADO data in PBI and then I see this does such an incredible job off the shelf. Wow!

I have no problems through the PBI Desktop and will spend many a happy hour analysing project data over the next few days. 

However, if I publish to PBI Cloud I initially get no problem. But if I try to refresh data, either manually or scheduled, I get a duplicate value reported:

Data source error: Column 'Date' in Table 'Dates' contains a duplicate value '3/27/2022' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
Cluster URI: WABI-EUROPE-NORTH-B-redirect.analysis.windows.net
Activity ID: 7d69b1b1-39ad-43dc-b574-f8da030f314e
Request ID: d3dd2660-cb1a-939e-866c-e4f5da568551
Time: 2022-10-20 16:28:37Z

I've looked in the Dates table and there is no such duplicate record seen. Looking at the data query in the template I see nothing to address duplicates so am at a loss to understand why these appear in refreshing the data.

I've checked data source credentials for the published dataset. I can reproduce the error each time. It occurs on the first refresh of data published to the cloud.

I'm using the last published version of FlowViz from a couple of days ago, 1.1.6841, PBI 2.109.1021.0 64-bit (September 2022)

The above was on the free tier but I've just started a Pro trial and observe the same behaviour.

**Comment by nbrown02** [comment]
Thank you for the kind words and logging this. This is something that has come to fruition recently and have seen the same issue with some (but not all reports) in my current orgs workspace. The issue is something on the Microsoft end as, like you say, you can't see duplicates in Power BI. I have logged this [here](https://community.powerbi.com/t5/Issues/Duplicate-value-causing-refresh-issue-but-value-is-not/idc-p/2832994#M86542) but no fix provided.

There are workarounds, you can either:
- Change the relationships to be many to many or;
- Disable the dates table from data refresh (it will have dates to 31/12/2023 in the PBI file already)

Happy to provide screenshots with those if not sure how to do it :)

**Comment by matkinsonPB** [comment]
Huge thanks for the prompt response & guidance. The workaround of tuning off that table refresh is good for me. And thanks - I now know that option exists!

**Comment by nbrown02** [comment]
Not a problem - please leave a review in the ADO marketplace as well if you get a chance 😬
