### ISSUE TITLE
Forecast tab/page crashes with WebView2 error

### ISSUE THREAD

**Issue by devyous** [nbrown02/FlowViz#93]
**Describe the bug**
With 4500+ work items in a project the forecast tab/page crashes PowerBI Desktop before being able to select an Area Path. If already filtered the Area Path in the transform data section, however I’m not a PowerBI Desktop expert, so I don’t know if all the work items are still loaded under the hood.

This error occurs even after changing PowerBI Desktop’s language to English-US as per previous bug reports.

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit
 - Browser Latest Edge
 - Version Latest PowerBI Desktop

**Comment by nbrown02** [comment]
Unfortunately there is no way I can account for this big a project for little old me doing this by myself! 

There are templates I have that can filter by [Area Path ](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Area%20Path%20Filter.pbit) or [Team.](https://github.com/nbrown02/FlowViz/raw/main/Screenshots/FlowViz%20(Project)%20-%20Team%20Filter.pbit) in their queries - would these be a suitable workaround?

**Comment by nbrown02** [comment]
Yeah they were created as one offs that I don't publicly advertise 😬

There is minimal difference between them, only query tweaks and like you spotted, dark mode is missing. I don't intend on adding this in right now just because it's quite an overhead with the bookmarks!

If there are significant changes (eg new charts, significant bug fixes) then I'll publish a new version :)
