### ISSUE TITLE
Error - Unable to connect to the Organization 

### ISSUE THREAD

**Issue by Iamthatsomebody** [nbrown02/FlowViz#96]
**Describe the bug**
I am unable to connect to my organization or Project. I have downloaded the latest Power BI Version: 2.115.1006.0 64-bit (March 2023). I have used this before connecting to the same organization without any issues. Now, am trying after a year to connect and it's not working. 

**To Reproduce**
1. Downloaded the Template file 
2. Open the .pbit file
3. Entered the Azure DevOps Server name & Organization name
4. See the error

**Expected behavior**
Data should be loaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/128010147/230980269-3a109a14-f981-4978-a099-7cbcc4b26b1f.png)

![image](https://user-images.githubusercontent.com/128010147/230980379-5144615d-ffc7-4872-bba9-b205b625ac82.png)

**Desktop (please complete the following information):**
 - OS : Windows
 - chrome

**Comment by nbrown02** [comment]
Hi,Please re-read the guidance for the analytics URL - this should be analytics.dev.azure.com not dev.azure.comThanks,NickSent from my iPhoneOn 10 Apr 2023, at 20:25, Iamthatsomebody ***@***.***> wrote:﻿
Describe the bug
I am unable to connect to my organization or Project. I have downloaded the latest Power BI Version: 2.115.1006.0 64-bit (March 2023). I have used this before connecting to the same organization without any issues. Now, am trying after a year to connect and it's not working.
To Reproduce
Steps to reproduce the behavior:

Downloaded the Template file
Open the .pbit file
Entered the Azure DevOps Server name & Organization name
See the error

Expected behavior
Data should be loaded.
Screenshots


Desktop (please complete the following information):

OS : Windows
chrome

**Comment by Iamthatsomebody** [comment]
I tried what you mentioned, but it's still throwing me the error. 

![image](https://user-images.githubusercontent.com/128010147/230982855-9e6faa44-51bf-42a1-9acc-7f685cd7c289.png)

![image](https://user-images.githubusercontent.com/128010147/230982890-6a2af32b-6658-45ac-9b9f-79d4f68df640.png)

**Comment by nbrown02** [comment]
Sorry but can you please re-read the guidance as both these examples suggest that you are not following the instructions.You should also be using the project template if you are trying to generate this for a single ADO project.Thanks,Sent from my iPhoneOn 10 Apr 2023, at 20:38, Iamthatsomebody ***@***.***> wrote:﻿
I tried what you mentioned, but it's still throwing me the error.

**Comment by Iamthatsomebody** [comment]
Sorry, I have re-read the guidance and tried both. I just sent you the error for one. As I mentioned in my first comment I am unable to connect to both Organization and a single ADO project. 

![image](https://user-images.githubusercontent.com/128010147/230987698-e6aa8165-498c-47a6-a9a8-c50233623521.png)

![image](https://user-images.githubusercontent.com/128010147/230987753-c1866f62-b65d-48ad-bd1d-b4d072b8ce66.png)

I really need this to work. Please let me know what can be done. Thanks

**Comment by nbrown02** [comment]
As per the guidance, you should simply enter “analytics.dev.azure.com” for the Analytics URL. Then you should enter your organisation (in the organisation field) and then your project (in the project field). Please try to understand my frustration, as you have ignored this in every screenshot you have sent to me…Sent from my iPhoneOn 10 Apr 2023, at 21:05, Iamthatsomebody ***@***.***> wrote:﻿
Sorry, I have re-read the guidance and tried both. I just sent you the error for one. As I mentioned in my first comment I am unable to connect to both Organization and a single ADO project.


I really need this to work. Please let me know what can be done. Thanks

**Comment by Iamthatsomebody** [comment]
I am really sorry to frustrate you. It got connected, thanks for your guidance.
